// Mock vaccine data for offline/development testing
export const mockVaccineData = [
  {
    VaccineDetailID: 1,
    VaccineCode: "COVID-19-001",
    VaccineName: "Pfizer-BioNTech COVID-19",
    Manufacturer: "Pfizer/BioNTech",
    CountryOfOrigin: "USA/Germany",
    DosePerVial: 5,
    Description: "mRNA vaccine against COVID-19 (Comirnaty). Requires 2 doses, 21 days apart.",
    IsActive: true,
  },
  {
    VaccineDetailID: 2,
    VaccineCode: "COVID-19-002",
    VaccineName: "Moderna COVID-19",
    Manufacturer: "Moderna",
    CountryOfOrigin: "USA",
    DosePerVial: 10,
    Description: "mRNA vaccine against COVID-19. Requires 2 doses, 28 days apart.",
    IsActive: true,
  },
  {
    VaccineDetailID: 3,
    VaccineCode: "COVID-19-003",
    VaccineName: "AstraZeneca COVID-19",
    Manufacturer: "AstraZeneca/Oxford",
    CountryOfOrigin: "UK/Sweden",
    DosePerVial: 10,
    Description: "Viral vector vaccine against COVID-19. Requires 2 doses, 8-12 weeks apart.",
    IsActive: true,
  },
  {
    VaccineDetailID: 4,
    VaccineCode: "POLIO-001",
    VaccineName: "Polio (IPV)",
    Manufacturer: "Sanofi Pasteur",
    CountryOfOrigin: "France",
    DosePerVial: 1,
    Description: "Inactivated Poliovirus Vaccine. Part of routine childhood immunization. 3 doses needed.",
    IsActive: true,
  },
  {
    VaccineDetailID: 5,
    VaccineCode: "MMR-001",
    VaccineName: "MMR (Measles, Mumps, Rubella)",
    Manufacturer: "Merck Sharp & Dohme",
    CountryOfOrigin: "USA",
    DosePerVial: 1,
    Description: "Live attenuated vaccine for measles, mumps, and rubella. 2 doses recommended.",
    IsActive: true,
  },
  {
    VaccineDetailID: 6,
    VaccineCode: "DPT-001",
    VaccineName: "DPT (Diphtheria, Pertussis, Tetanus)",
    Manufacturer: "Sanofi Pasteur",
    CountryOfOrigin: "France",
    DosePerVial: 1,
    Description: "Combined vaccine for Diphtheria, Pertussis (Whooping Cough), and Tetanus. 5 doses in childhood.",
    IsActive: true,
  },
  {
    VaccineDetailID: 7,
    VaccineCode: "FLU-2024",
    VaccineName: "Influenza Vaccine 2024",
    Manufacturer: "GSK",
    CountryOfOrigin: "UK",
    DosePerVial: 1,
    Description: "Seasonal influenza vaccine. Updated annually. 1-2 doses depending on age.",
    IsActive: true,
  },
  {
    VaccineDetailID: 8,
    VaccineCode: "HEPB-001",
    VaccineName: "Hepatitis B",
    Manufacturer: "Merck",
    CountryOfOrigin: "USA",
    DosePerVial: 1,
    Description: "Vaccine against Hepatitis B virus. 3 doses required (0, 1, 6 months).",
    IsActive: true,
  },
  {
    VaccineDetailID: 9,
    VaccineCode: "CHICK-001",
    VaccineName: "Chickenpox (Varicella)",
    Manufacturer: "Merck",
    CountryOfOrigin: "USA",
    DosePerVial: 1,
    Description: "Live attenuated vaccine for chickenpox. 2 doses recommended.",
    IsActive: true,
  },
  {
    VaccineDetailID: 10,
    VaccineCode: "YF-001",
    VaccineName: "Yellow Fever",
    Manufacturer: "Sanofi Pasteur",
    CountryOfOrigin: "France",
    DosePerVial: 1,
    Description: "Live attenuated vaccine for yellow fever. 1 dose, valid for life. Required for travel to endemic areas.",
    IsActive: true,
  },
];

export const mockVaccineLots = [
  {
    LotID: 1,
    LotCode: "LOT-COVID-001-2023",
    VaccineDetailID: 1,
    ManufactureDate: "2023-09-10",
    ExpiryDate: "2025-06-10",
    TotalQuantity: 1000,
    RemainingQuantity: 850,
    LotStatus: "IN_STOCK",
  },
  {
    LotID: 2,
    LotCode: "LOT-COVID-001-2024",
    VaccineDetailID: 1,
    ManufactureDate: "2024-02-08",
    ExpiryDate: "2025-12-08",
    TotalQuantity: 500,
    RemainingQuantity: 500,
    LotStatus: "IN_STOCK",
  },
  {
    LotID: 3,
    LotCode: "LOT-MOD-001-2024",
    VaccineDetailID: 2,
    ManufactureDate: "2023-12-23",
    ExpiryDate: "2025-11-23",
    TotalQuantity: 800,
    RemainingQuantity: 750,
    LotStatus: "IN_STOCK",
  },
  {
    LotID: 4,
    LotCode: "LOT-AZ-001-2024",
    VaccineDetailID: 3,
    ManufactureDate: "2023-12-08",
    ExpiryDate: "2025-12-08",
    TotalQuantity: 600,
    RemainingQuantity: 580,
    LotStatus: "IN_STOCK",
  },
  {
    LotID: 5,
    LotCode: "LOT-POLIO-001-2024",
    VaccineDetailID: 4,
    ManufactureDate: "2023-11-08",
    ExpiryDate: "2025-11-08",
    TotalQuantity: 2000,
    RemainingQuantity: 1900,
    LotStatus: "IN_STOCK",
  },
  {
    LotID: 6,
    LotCode: "LOT-MMR-001-2024",
    VaccineDetailID: 5,
    ManufactureDate: "2023-10-08",
    ExpiryDate: "2025-10-08",
    TotalQuantity: 1500,
    RemainingQuantity: 1300,
    LotStatus: "IN_STOCK",
  },
];
